import time
#basically just a caculator but bad for some reason
print(".................................................")
print("Addition")
number1 = float(input("Enter first number here: "))
number2 = float(input("Enter second number here: "))
print(number1 + number2)
print(".................................................")
time.sleep(1)
print(",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,")
print("Subtraction")
number3 = float(input("Enter first number here: "))
number4 = float(input("Enter second number here: "))
print(number3 - number4)
print(",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,")
time.sleep(1)
print(".................................................")
print("Multiplication")
number5 = float(input("Enter first number here: "))
number6 = float(input("Enter second number here: "))
print(number5 * number6)
print(".................................................")
time.sleep(1)
print(",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,")
print("Division")
number7 = float(input("Enter first number here: "))
number8 = float(input("Enter second number here: "))
print(number7 / number8)
print(",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,")